import type { Metadata } from "next";
import Link from "next/link";
import {
  getDailyFortune,
  getAllFortunes,
  getRarityColor,
  getRarityLabel,
  getFortuneNumber,
  seededRandom,
  Fortune,
} from "@/lib/fortuneEngine";
import { BreadcrumbJsonLd, FAQPageJsonLd } from "@/components/JsonLd";
import { SITE_URL, SITE_NAME } from "@/lib/constants";

export const revalidate = 43200; // 12 hours — refresh at least twice daily

export const metadata: Metadata = {
  title: "Daily Fortune Cookie",
  description:
    "Get your free daily fortune cookie message! A new fortune every day, the same for everyone worldwide. Discover today's wisdom, reflect on its meaning, and start your day with intention.",
  alternates: {
    canonical: `${SITE_URL}/daily`,
  },
  openGraph: {
    title: `Daily Fortune Cookie | ${SITE_NAME}`,
    description:
      "Get your free daily fortune cookie message! A new fortune every day, the same for everyone worldwide.",
    url: `${SITE_URL}/daily`,
  },
  twitter: {
    card: "summary_large_image",
    title: `Daily Fortune Cookie | ${SITE_NAME}`,
    description:
      "Get your free daily fortune cookie message! A new fortune every day, the same for everyone worldwide.",
  },
};

const faqs = [
  {
    q: "How is the daily fortune selected?",
    a: "The daily fortune uses a date-seeded pseudorandom number generator called mulberry32. The current date (year, month, day) is converted into a numeric seed, which produces a deterministic sequence of random numbers. This means every visitor anywhere in the world sees the exact same fortune on the same day, and a new fortune appears automatically at midnight UTC.",
  },
  {
    q: "Does the daily fortune repeat?",
    a: "With over 1,000 fortunes in our database and a mathematically distributed selection algorithm, it takes years before the same fortune appears as the daily pick again. Each day's seed produces a unique index into the full fortune pool, so repetition is extremely rare.",
  },
  {
    q: "What time does the daily fortune change?",
    a: "The daily fortune changes at midnight UTC (Coordinated Universal Time). Depending on your time zone, this may be evening, midnight, or early morning in your local time. For example, midnight UTC is 7:00 PM Eastern Time and 4:00 PM Pacific Time on the previous calendar day.",
  },
  {
    q: "Can I see previous daily fortunes?",
    a: "Yes! This page displays a 7-day history of recent daily fortunes, so you can review the past week's messages. Each fortune is generated from the date seed for that specific day, ensuring accuracy even when viewed retroactively.",
  },
  {
    q: "Why does everyone see the same daily fortune?",
    a: "The shared daily fortune creates a sense of collective experience. Just as a daily horoscope or newspaper quote of the day connects readers through a common message, our daily fortune gives everyone a shared starting point for reflection. It also makes the fortune easy to discuss with friends and family.",
  },
  {
    q: "Is the daily fortune truly random?",
    a: "The daily fortune is pseudorandom, meaning it is generated by a mathematical algorithm (mulberry32) rather than true randomness. However, the output is uniformly distributed across all fortunes and is unpredictable to humans. The key property is determinism: the same date always produces the same fortune, which is what allows the shared global experience.",
  },
];

function getFortuneForDate(daysAgo: number): { fortune: Fortune; date: Date } {
  const date = new Date();
  date.setUTCDate(date.getUTCDate() - daysAgo);
  const seed =
    date.getUTCFullYear() * 10000 +
    (date.getUTCMonth() + 1) * 100 +
    date.getUTCDate();
  const rng = seededRandom(seed);

  const allFortunes = getAllFortunes();
  const index = Math.floor(rng() * allFortunes.length);
  return { fortune: allFortunes[index], date };
}

export default function DailyFortunePage() {
  const todayFortune = getDailyFortune();
  const rarityColor = getRarityColor(todayFortune.rarity);
  const rarityLabel = getRarityLabel(todayFortune.rarity);
  const fortuneNumber = getFortuneNumber(todayFortune.text);

  const today = new Date();
  const dateStr = today.toLocaleDateString("en-US", {
    weekday: "long",
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  // Build 7-day history (excluding today)
  const history: { fortune: Fortune; date: Date }[] = [];
  for (let i = 1; i <= 7; i++) {
    history.push(getFortuneForDate(i));
  }

  return (
    <div className="bg-warm-gradient min-h-screen px-4 py-16">
      <BreadcrumbJsonLd
        items={[
          { name: "Home", url: SITE_URL },
          { name: "Daily Fortune", url: `${SITE_URL}/daily` },
        ]}
      />
      <FAQPageJsonLd faqs={faqs} />

      <article className="mx-auto max-w-2xl">
        <div className="text-center mb-10">
          <div className="text-6xl mb-4">&#127808;</div>
          <h1 className="text-golden-shimmer text-3xl sm:text-4xl font-bold mb-2">
            Daily Fortune Cookie
          </h1>
          <p className="text-muted text-sm">{dateStr}</p>
          <p className="text-muted text-xs mt-1">
            Fortune #{fortuneNumber}
          </p>
        </div>

        {/* Today's Fortune */}
        <div
          className="relative overflow-hidden rounded-2xl border p-5 sm:p-8 text-center mb-8"
          style={{
            borderColor: rarityColor + "30",
            background: `radial-gradient(ellipse at center, ${rarityColor}08 0%, transparent 70%)`,
          }}
        >
          <div className="absolute left-3 top-3 text-gold/30">&#10022;</div>
          <div className="absolute right-3 top-3 text-gold/30">&#10022;</div>
          <div className="absolute bottom-3 left-3 text-gold/30">&#10022;</div>
          <div className="absolute bottom-3 right-3 text-gold/30">&#10022;</div>
          <p className="text-xs uppercase tracking-wider text-foreground/30 mb-4">
            Today&apos;s Fortune
          </p>
          <p className="font-serif text-xl leading-relaxed text-cream">
            &ldquo;{todayFortune.text}&rdquo;
          </p>
          <div className="mt-4 flex items-center justify-center gap-3">
            <span
              className="rounded-full px-3 py-1 text-xs font-semibold text-white"
              style={{ backgroundColor: rarityColor }}
            >
              {rarityLabel}
            </span>
            <span className="text-xs capitalize text-muted">
              {todayFortune.category}
            </span>
          </div>
        </div>

        {/* CTA */}
        <div className="text-center mb-12">
          <Link
            href="/"
            className="inline-block rounded-full bg-gold px-8 py-3 font-semibold text-background transition hover:bg-gold-light"
          >
            Break a Fortune Cookie
          </Link>
        </div>

        {/* 7-Day History */}
        <div className="rounded-2xl border border-border bg-background p-6 mb-8">
          <h2 className="text-lg font-semibold text-gold mb-4">
            Past 7 Days
          </h2>
          <div className="space-y-3">
            {history.map(({ fortune, date }, i) => {
              const dayStr = date.toLocaleDateString("en-US", {
                weekday: "short",
                month: "short",
                day: "numeric",
              });
              const histRarityColor = getRarityColor(fortune.rarity);
              return (
                <div
                  key={i}
                  className="flex items-start gap-3 rounded-lg border border-border bg-background px-4 py-3"
                >
                  <div className="shrink-0 text-xs text-muted pt-0.5 w-20">
                    {dayStr}
                  </div>
                  <div className="flex-1 text-sm text-foreground/70">
                    &ldquo;{fortune.text}&rdquo;
                  </div>
                  <div
                    className="shrink-0 h-2 w-2 rounded-full mt-1.5"
                    style={{ backgroundColor: histRarityColor }}
                    title={getRarityLabel(fortune.rarity)}
                  />
                </div>
              );
            })}
          </div>
        </div>

        {/* Educational Section: How the Daily Fortune Algorithm Works */}
        <section className="rounded-2xl border border-border bg-background p-6 mb-8">
          <h2 className="text-lg font-semibold text-gold mb-3">
            How the Daily Fortune Algorithm Works
          </h2>
          <div className="space-y-3 text-sm text-muted leading-relaxed">
            <p>
              Every day at midnight UTC, a new fortune appears on this page, and it is identical for every
              visitor on Earth. This is not a coincidence or a trick of caching. It is the result of a
              deterministic pseudorandom number generator called mulberry32, a compact algorithm widely used
              in procedural generation for games, simulations, and creative coding. The algorithm takes a
              single numeric seed and produces a sequence of numbers that appears random but is entirely
              reproducible. Given the same seed, it will always produce the same sequence, on any device,
              in any browser, in any country.
            </p>
            <p>
              The seed for each day is constructed from the calendar date: the four-digit year is multiplied
              by ten thousand, the month (one through twelve) is multiplied by one hundred, and the day of
              the month is added. For example, March 1, 2026 produces the seed 20260301. This seed is fed
              into mulberry32, which generates a floating-point number between zero and one. That number is
              then multiplied by the total number of fortunes in the database — currently over 1,000 — and
              the result is floored to produce an integer index. The fortune at that index becomes the daily
              fortune. Because the seed changes only when the date changes, the fortune remains stable for
              a full 24-hour window before rotating to the next one.
            </p>
            <p>
              This approach is deliberately different from server-side random selection, where each page load
              might produce a different result. The date-seeded method creates a shared experience: you and
              a friend in a different time zone can compare fortunes and discover you received the same
              message. This design borrows from games like Wordle, which popularized the concept of a single
              daily puzzle that unites players around a common challenge. The daily fortune extends that idea
              to a reflective, fortune-based ritual rather than a competitive one.
            </p>
          </div>
        </section>

        {/* Educational Section: The Psychology of Daily Rituals */}
        <section className="rounded-2xl border border-border bg-background p-6 mb-8">
          <h2 className="text-lg font-semibold text-gold mb-3">
            The Psychology Behind Daily Rituals
          </h2>
          <div className="space-y-3 text-sm text-muted leading-relaxed">
            <p>
              The act of checking a daily fortune may seem like a small, lighthearted gesture, but
              behavioral psychology suggests that small daily rituals carry disproportionate influence on
              well-being and habit formation. Research on habit loops, popularized by Charles Duhigg in
              <em> The Power of Habit</em>, shows that consistent cue-routine-reward cycles are the
              foundation of lasting behavioral change. A daily fortune can serve as the cue that initiates
              a morning reflection routine, with the fortune itself providing a small reward of novelty
              and curiosity. Over time, this loop becomes automatic, and the reflection deepens without
              requiring additional willpower.
            </p>
            <p>
              The Zeigarnik effect, discovered by psychologist Bluma Zeigarnik in 1927, describes the
              mind&apos;s tendency to remember incomplete tasks and unresolved thoughts more vividly than
              completed ones. A well-crafted fortune — especially one that is slightly ambiguous or
              thought-provoking — creates a gentle form of cognitive incompleteness. Your mind returns to
              it throughout the day, seeking connections between the fortune&apos;s message and your lived
              experience. This is not a flaw in cognition; it is a feature. The fortune becomes a lens
              through which you notice things you might otherwise overlook, a thread that ties together
              otherwise disconnected moments into a more intentional narrative.
            </p>
            <p>
              Positive psychology research by Martin Seligman and others has demonstrated that brief daily
              interventions — writing three good things, expressing gratitude, or reflecting on a meaningful
              phrase — can measurably improve mood, resilience, and life satisfaction over periods as short
              as two weeks. A daily fortune functions as exactly this kind of micro-intervention. It arrives
              unbidden, requires no preparation, and offers a fresh perspective that the conscious mind did
              not choose. This element of surprise is psychologically important: self-selected affirmations
              can feel forced, but a randomly assigned message bypasses the inner critic and feels more like
              a genuine gift from the universe — or at least from a well-designed algorithm.
            </p>
          </div>
        </section>

        {/* Educational Section: Daily Fortune Reading Across Cultures */}
        <section className="rounded-2xl border border-border bg-background p-6 mb-8">
          <h2 className="text-lg font-semibold text-gold mb-3">
            Daily Fortune Reading Across Cultures
          </h2>
          <div className="space-y-3 text-sm text-muted leading-relaxed">
            <p>
              The practice of seeking daily guidance from oracles, divination tools, or sacred texts is one
              of humanity&apos;s most enduring traditions, spanning every inhabited continent and thousands of
              years of recorded history. In ancient China, the I Ching (Book of Changes) was consulted not
              just for major decisions but as a daily practice of self-reflection. Scholars and officials would
              cast yarrow stalks each morning to receive a hexagram whose interpretation guided their conduct
              for the day. This was not considered superstition by educated practitioners but rather a
              structured method for cultivating self-awareness and mindful decision-making. The fortune cookie,
              which emerged in early twentieth-century California through Japanese-American and Chinese-American
              culinary traditions, inherited this impulse and compressed it into a single sentence delivered
              inside a crisp, folded wafer.
            </p>
            <p>
              In Japan, the tradition of omikuji — paper fortune slips drawn at Shinto shrines and Buddhist
              temples — remains a beloved daily and seasonal practice. Visitors shake a cylindrical box to
              draw a numbered stick, then receive the corresponding fortune, which ranges from great blessing
              (daikichi) to great curse (daikyo). Bad fortunes are tied to a pine tree or wire rack at the
              shrine, symbolically leaving the misfortune behind. This ritual beautifully illustrates the
              psychological function of daily fortune reading: it externalizes anxiety, gives form to
              uncertainty, and provides a concrete action (tying the paper) that restores a sense of
              agency. Japanese omikuji culture directly influenced the design of fortune cookies, which
              were first baked by Japanese-American confectioners in San Francisco and Los Angeles before
              becoming associated primarily with Chinese-American restaurants.
            </p>
            <p>
              Western traditions of daily divination include bibliomancy — opening a sacred book at random
              and reading the first passage your eyes land on — practiced with the Bible, the works of Virgil,
              and later with the collected poems of Hafez in Persian culture. The concept of a &ldquo;daily
              oracle card&rdquo; draw has become popular in modern spiritual practice, where a single tarot
              card or oracle card is pulled each morning as a theme for the day. What all these traditions
              share is the belief that a brief encounter with a meaningful message, delivered by a process
              the individual does not control, can orient attention and intention in beneficial ways. The
              daily fortune cookie carries forward this ancient practice in a digital, secular, and
              universally accessible format — no shrine visit required, just an internet connection and a
              moment of openness.
            </p>
          </div>
        </section>

        {/* Educational Section: Using Your Daily Fortune as a Reflection Prompt */}
        <section className="rounded-2xl border border-border bg-background p-6 mb-8">
          <h2 className="text-lg font-semibold text-gold mb-3">
            How to Use Your Daily Fortune as a Reflection Prompt
          </h2>
          <div className="space-y-3 text-sm text-muted leading-relaxed">
            <p>
              A daily fortune gains its deepest value not from passive reading but from active engagement.
              Here is a simple four-step practice you can complete in under five minutes each morning. First,
              read the fortune once and notice your immediate emotional reaction — curiosity, skepticism,
              recognition, amusement. That gut response often reveals what the fortune means to you more
              accurately than any intellectual analysis. Second, ask yourself a single question: &ldquo;Where
              in my life does this message apply right now?&rdquo; Let your mind wander freely; the first
              connection that surfaces is usually the most authentic. Third, write the fortune down — on a
              sticky note, in a journal, or in your phone&apos;s notes app. The physical act of transcribing
              a message deepens encoding and makes it more likely you will recall it later. Fourth, return
              to the fortune at the end of the day and reflect on whether it intersected with any of your
              experiences. You may be surprised by how often a morning fortune echoes in an afternoon
              conversation or an evening decision.
            </p>
            <p>
              Over time, this practice builds what psychologists call &ldquo;reflective self-awareness&rdquo;
              — the capacity to observe your own thoughts, emotions, and behaviors with curiosity rather than
              judgment. It also creates a personal archive of daily themes that, when reviewed over weeks or
              months, can reveal patterns in your preoccupations, aspirations, and growth. Some practitioners
              keep a dedicated &ldquo;fortune journal&rdquo; where they paste or write each day&apos;s
              fortune alongside a sentence or two of reflection. This journal becomes a unique autobiography
              — not of events, but of inner life, filtered through the lens of daily chance encounters with
              meaning. The daily fortune is a mirror, and what you see in it tells you more about yourself
              than about the fortune.
            </p>
          </div>
        </section>

        {/* Visible FAQ Section */}
        <section className="rounded-2xl border border-border bg-background p-6 mb-8">
          <h2 className="text-lg font-semibold text-gold mb-4">
            Frequently Asked Questions
          </h2>
          <div className="space-y-5">
            {faqs.map((faq, i) => (
              <div key={i}>
                <h3 className="text-sm font-semibold text-foreground/80 mb-1">
                  {faq.q}
                </h3>
                <p className="text-sm text-muted leading-relaxed">{faq.a}</p>
              </div>
            ))}
          </div>
        </section>

        {/* Related Links */}
        <div className="border-t border-border pt-8">
          <h2 className="text-lg font-semibold text-gold mb-4 text-center">
            More Fortune Fun
          </h2>
          <div className="flex flex-wrap justify-center gap-3">
            <Link
              href="/lucky-numbers"
              className="rounded-full border border-border px-4 py-2.5 text-sm text-muted transition hover:border-gold/30 hover:text-gold"
            >
              Lucky Numbers
            </Link>
            <Link
              href="/horoscope"
              className="rounded-full border border-border px-4 py-2.5 text-sm text-muted transition hover:border-gold/30 hover:text-gold"
            >
              Daily Horoscopes
            </Link>
            <Link
              href="/zodiac/aries"
              className="rounded-full border border-border px-4 py-2.5 text-sm text-muted transition hover:border-gold/30 hover:text-gold"
            >
              Zodiac Fortunes
            </Link>
            <Link
              href="/fortune/wisdom"
              className="rounded-full border border-border px-4 py-2.5 text-sm text-muted transition hover:border-gold/30 hover:text-gold"
            >
              Fortune Categories
            </Link>
            <Link
              href="/blog"
              className="rounded-full border border-border px-4 py-2.5 text-sm text-muted transition hover:border-gold/30 hover:text-gold"
            >
              Blog
            </Link>
          </div>
        </div>
      </article>
    </div>
  );
}
